### ISSUE TITLE
Update CakePHP

### ISSUE THREAD

**Issue by kousu** [santropolroulant/volunteerdb#1]
This project was written 6 years ago and CakePHP has had many many revisions since then.

**Comment by kousu** [comment]
I just tried running this code on php7.2 and got a big angry traceback:

```

( ! ) Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/feastdb/public/vol2/lib/Cake/Core/Object.php on line 26
Call Stack
#	Time	Memory	Function	Location
1	0.0007	396472	{main}( )	.../index.php:0
2	0.0197	398512	include( '/var/www/feastdb/public/vol2/lib/Cake/bootstrap.php' )	.../index.php:77
3	0.0496	591544	Configure::bootstrap( )	.../bootstrap.php:146
4	0.0679	743480	class_exists ( )	.../Configure.php:105
5	0.0679	743512	spl_autoload_call ( )	.../Configure.php:105
6	0.0679	743544	App::load( )	.../Configure.php:105
7	0.0686	883088	App::shutdown( )	.../App.php:0
8	0.0687	883080	App::_checkFatalError( )	.../App.php:899
9	0.0688	883760	ErrorHandler::handleError( )	.../App.php:926
10	0.0688	883760	ErrorHandler::handleFatalError( )	.../ErrorHandler.php:161
11	0.0837	886888	ErrorHandler::handleException( )	.../ErrorHandler.php:211
12	0.1015	889880	ExceptionRenderer->__construct( )	.../ErrorHandler.php:125
13	0.1015	889880	ExceptionRenderer->_getController( )	.../ExceptionRenderer.php:93
14	0.1085	966696	spl_autoload_call ( )	.../ExceptionRenderer.php:157
15	0.1085	966736	App::load( )	.../ExceptionRenderer.php:157
16	0.1109	972464	include( '/var/www/feastdb/public/vol2/lib/Cake/Controller/Controller.php' )	.../App.php:560
17	0.1109	973744	spl_autoload_call ( )	.../Controller.php:56
18	0.1109	973776	App::load( )	.../Controller.php:56
```

And on php7.0 it gets further but still chokes with

> Fatal Error
>
> Error: Cannot use 'String' as class name as it is reserved
> File: /var/www/feastdb/public/vol2/lib/Cake/Utility/String.php
> Line: 26
> 
> Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp

**Comment by kousu** [comment]
There's a [migration guide](https://book.cakephp.org/3.0/en/appendices/3-0-migration-guide.html) to go from 2.x -> 3.0, and [further guides](https://book.cakephp.org/3.0/en/appendices/3-x-migration-guide.html) for the minor steps. Right now I'm guess that the best path is to go to 3.0 and then go step by step after that.

3.0 [rearranges the folder structure](https://github.com/cakephp/app) and [replaces the ORM](https://book.cakephp.org/3.0/en/appendices/orm-migration.html), so just getting those working are going to be a pretty big change, I think.

**Comment by kousu** [comment]
In the old app layout, CakePHP was installed to `lib/`; now it's expected to be installed to `vendor/` by [Composer](https://getcomposer.org/). 

It seems like, thankfully (and correctly), no changes were made to CakePHP:

```
[nguenthe@papyrus volunteerdb]$ git log lib
commit 4e3bf873559dbffa7e1cf9f5da3e6750900619a5
Author: Nick Guenther <kousu@santropolroulant.org>
Date:   Thu May 31 02:39:44 2018 -0400

    Run CakePHP 2-to-3 migration tool.
    
    From https://github.com/cakephp/upgrade

commit b0bc3584a2b7aa64ea0f6c3d3104de2b0f424b16
Author: itsupport <itsupport@santropolroulant.org>
Date:   Thu Oct 11 20:00:30 2012 +0530

    Import CakePHP
```

**Comment by kousu** [comment]
Note to self: @connorbode has included a Dockerfile; I need to double-check that's still working after the upgrade.

**Comment by kousu** [comment]
Let's index what was modified in the original app skeleton:

```
diff -ru dssd/ ../santropol/volunteerdb/app/ > skel.patch.txt
```

[skel.patch.txt](https://github.com/santropolroulant/volunteerdb/files/2065470/skel.patch.txt)

**Comment by kousu** [comment]
So we need to investigate:

1. Config/
2. Controller/
3. .htaccess
4. Model/
5. tmp/ ( which ... couldn't possibly actually matter, right? )
6. View/

The Views are where most of the work is; they're essentially all the HTML pages. It's also likely that most of them are new files so mostly they shouldn't conflict with the [updated app skeleton](https://github.com/cakephp/app/). Indeed, looking at it, all the changes are to app/View/Volunteers/* and app/View/Elements/flash_*.ctp, but for app/View/Layouts/default.ctp which [is going to conflict](https://github.com/cakephp/app/blob/master/src/Template/Layout/default.ctp) --- but I think we should just not worry about it, because that's probably the master layout template, and whatever @nicolaskruchten decided was best should rule; anyway, the original default.ctp is pretty short so if there is anything to learn from it we should be able to figure it out quick.

Config is where the next largest batch of work is; but investigating, that's actually mostly the helper functions that @nicolaskruchten dumped into bootstrap.php -- they're not really configuration changes, so again that shouldn't conflict -- though I might need a manual merging, and probably those functions should be pulled elsewhere (Plugins/?).

The edits to tmp are just setting file permissions, which are probably an artifact of the upgrade tool or something anyway, so I'll ignore that.

.htaccess only get edited incidentally: "\ No newline at end of file", so that's ignorable.

Model/ just adds a new file, Volunteer.php, which is the backing for app/View/Volunteer/, so that's no conflict.

**Comment by kousu** [comment]
How are we supposed to set the seed in deployment? It's generated during `composer install cakephp`.

I looked at my demo folder, and apparently it _copies_ app.default.php and makes one edit to it, putting a generated salt into it. I think what you're supposed to do, guessing a bit here because I'm not usually a php programmer and certainly not a modern dependency-managed(!) php programmer, but I think you're supposed to edit app.default.php to set any important settings, then `git clone` the repo to a server, then `composer install` in the root which reads composer.json. So that's actually not too bad.

**Comment by kousu** [comment]
And after all the file updates, I probably have to go read that [ORM migration guide](https://book.cakephp.org/3.0/en/appendices/orm-migration.html) and change the Model files a bunch.

**Comment by kousu** [comment]
I almost feel like, given that there's really not very much code here to worry about, it might almost be easier to `rm` all files, start from the app template, and reinstall the Volunteers Model/View/Controller files; I would (might?) lose the git history though.

**Comment by kousu** [comment]
Okay! Progress!

```
$ composer install
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> App\Console\Installer::postInstall
Created `config/app.php` file
...
Updated Security.salt value in config/app.php
$
$ php index.php 
PHP Fatal error:  Class 'app\Controller\AppController' not found in volunteerdb/src/Controller/VolunteersController.php on line 4

Fatal error: Class 'app\Controller\AppController' not found in volunteerdb/src/Controller/VolunteersController.php on line 4
Fatal Error: Class 'app\Controller\AppController' not found in [volunteerdb/src/Controller/VolunteersController.php, line 4]
```

It's not working, but it's obvious why it's not working: the old code needs patching.

**Comment by kousu** [comment]
ORM updates:

* Tables are pluralized now: so everything $this->Volunteer needs to become $this->Volunteers, and every "Volunteer.property" needs to be "Volunteers.property"
* Model::read() is gone; instead you have to execute a query by calling ->first()

**Comment by kousu** [comment]
›           $this->Session->setFlash('Deleted.', 'flash_success');
^ this is probably going to need editing since I used Template/Element/Flash/success.ctp not Template/Element/flash_success.ctp.

**Comment by kousu** [comment]
Other updates needed:

[`$this->webroot` => `$this->request->webroot`](https://stackoverflow.com/questions/29216856/how-to-get-this-webroot-work-in-cakephp-3-0); otherwise you get this very strange error

```
Error: webrootHelper could not be found.
Error: Create the class webrootHelper below in file: src/View/Helper/webrootHelper.php

<?php
namespace App\View\Helper;

use Cake\View\Helper;

class webrootHelper extends Helper
{

}
```

**Comment by kousu** [comment]
[`$this->request->data`](https://book.cakephp.org/2.0/en/core-libraries/helpers/form.html) doesn't [seem](https://book.cakephp.org/3.0/en/search.html?check_keywords=yes&area=default&q=this-%3Erequest-%3Edata) to be in use anymore?

I've got the edit form rendering but it won't fill in data from the database. What do?

**Comment by kousu** [comment]
There's a weirdness with birthdays (see #5 for initial source of weirdness): if you edit a volunteer that doesn't have a birthday then it ends up saving their birthday as (null, 1, null) because _the default for birthmonth is January_, there's no null option, and then when you get bounced to `view/`  `<?php $age = (new DateTime($v['birthyear'] . '-' . $v['birthmonth'] . '-' . $v['birthday']))->diff(....`  crashes, because it runs `new DateTime("-1-")`.

Is this bug in the pre-3.0 install??

**Comment by nicolaskruchten** [comment]
Wow, ambitious upgrade! Looking forward to seeing how it ends up :)

**Comment by kousu** [comment]
**TODO**: the HTML pages are all under src/Template/Volunteers/*.ctp but there's also a src/View folder. Doesn't "Template" seem like the wrong place? Templates are for, say, default.ctp, the outer layout wrappers, not the actual views.

**Comment by kousu** [comment]
I've got it working locally in https://github.com/santropolroulant/volunteerdb/tree/migrate-to-3.

Still to do:

* replace all the calls in the views to `$this->request->getAttribute("webroot") . $something`  with [`Router::url()`](https://book.cakephp.org/3.0/en/development/routing.html#generating-urls) or [`Html::link()`](https://book.cakephp.org/3.0/en/views/helpers/html.html#linking-to-css-files)
* cleanup the form widgets on `edit.ctp` to use the [specialized calls](https://book.cakephp.org/3.0/en/views/helpers/form.html#Cake%5CView%5CHelper%5CFormHelper::text)
* dump and restore our live database as MySQL utf8mb4, which is real utf8, not the 3 byte thing MySQL misnamed utf8, cleaning up corrupted characters along the way
* maybe figure out what the deal with /edit being passed a POST for new volunteers but a PUT for edits to volunteers is

**Comment by kousu** [comment]
Reference on [MySQL encoding pain points](https://www.whitesmith.co/blog/latin1-to-utf8/)
